package com.dominator.entity;

public class AipOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.order_no
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.pay_amount
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.pay_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String payDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.return_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String returnDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.payment_order_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String paymentOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.merchant_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.version
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.ext1
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.ext2
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.pay_result
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String payResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.order_amount
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.order_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String orderDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.mcht_refund_order_no
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String mchtRefundOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.is_valid
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.refund_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String refundDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aip_order.product_name
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String productName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.order_no
     *
     * @return the value of aip_order.order_no
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.order_no
     *
     * @param orderNo the value for aip_order.order_no
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.pay_amount
     *
     * @return the value of aip_order.pay_amount
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.pay_amount
     *
     * @param payAmount the value for aip_order.pay_amount
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setPayAmount(String payAmount) {
        this.payAmount = payAmount == null ? null : payAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.pay_datetime
     *
     * @return the value of aip_order.pay_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getPayDatetime() {
        return payDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.pay_datetime
     *
     * @param payDatetime the value for aip_order.pay_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setPayDatetime(String payDatetime) {
        this.payDatetime = payDatetime == null ? null : payDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.return_datetime
     *
     * @return the value of aip_order.return_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getReturnDatetime() {
        return returnDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.return_datetime
     *
     * @param returnDatetime the value for aip_order.return_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setReturnDatetime(String returnDatetime) {
        this.returnDatetime = returnDatetime == null ? null : returnDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.payment_order_id
     *
     * @return the value of aip_order.payment_order_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getPaymentOrderId() {
        return paymentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.payment_order_id
     *
     * @param paymentOrderId the value for aip_order.payment_order_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setPaymentOrderId(String paymentOrderId) {
        this.paymentOrderId = paymentOrderId == null ? null : paymentOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.merchant_id
     *
     * @return the value of aip_order.merchant_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.merchant_id
     *
     * @param merchantId the value for aip_order.merchant_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.version
     *
     * @return the value of aip_order.version
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.version
     *
     * @param version the value for aip_order.version
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.ext1
     *
     * @return the value of aip_order.ext1
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.ext1
     *
     * @param ext1 the value for aip_order.ext1
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.ext2
     *
     * @return the value of aip_order.ext2
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.ext2
     *
     * @param ext2 the value for aip_order.ext2
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.pay_result
     *
     * @return the value of aip_order.pay_result
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getPayResult() {
        return payResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.pay_result
     *
     * @param payResult the value for aip_order.pay_result
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setPayResult(String payResult) {
        this.payResult = payResult == null ? null : payResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.order_amount
     *
     * @return the value of aip_order.order_amount
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.order_amount
     *
     * @param orderAmount the value for aip_order.order_amount
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount == null ? null : orderAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.order_datetime
     *
     * @return the value of aip_order.order_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getOrderDatetime() {
        return orderDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.order_datetime
     *
     * @param orderDatetime the value for aip_order.order_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setOrderDatetime(String orderDatetime) {
        this.orderDatetime = orderDatetime == null ? null : orderDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.mcht_refund_order_no
     *
     * @return the value of aip_order.mcht_refund_order_no
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getMchtRefundOrderNo() {
        return mchtRefundOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.mcht_refund_order_no
     *
     * @param mchtRefundOrderNo the value for aip_order.mcht_refund_order_no
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setMchtRefundOrderNo(String mchtRefundOrderNo) {
        this.mchtRefundOrderNo = mchtRefundOrderNo == null ? null : mchtRefundOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.is_valid
     *
     * @return the value of aip_order.is_valid
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.is_valid
     *
     * @param isValid the value for aip_order.is_valid
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.refund_datetime
     *
     * @return the value of aip_order.refund_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getRefundDatetime() {
        return refundDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.refund_datetime
     *
     * @param refundDatetime the value for aip_order.refund_datetime
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setRefundDatetime(String refundDatetime) {
        this.refundDatetime = refundDatetime == null ? null : refundDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aip_order.product_name
     *
     * @return the value of aip_order.product_name
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_order.product_name
     *
     * @param productName the value for aip_order.product_name
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }
}