package com.dominator.entity;

import java.util.ArrayList;
import java.util.List;

public class TblYeeLockUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public TblYeeLockUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andLockIdIsNull() {
            addCriterion("lock_id is null");
            return (Criteria) this;
        }

        public Criteria andLockIdIsNotNull() {
            addCriterion("lock_id is not null");
            return (Criteria) this;
        }

        public Criteria andLockIdEqualTo(String value) {
            addCriterion("lock_id =", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotEqualTo(String value) {
            addCriterion("lock_id <>", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdGreaterThan(String value) {
            addCriterion("lock_id >", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdGreaterThanOrEqualTo(String value) {
            addCriterion("lock_id >=", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdLessThan(String value) {
            addCriterion("lock_id <", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdLessThanOrEqualTo(String value) {
            addCriterion("lock_id <=", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdLike(String value) {
            addCriterion("lock_id like", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotLike(String value) {
            addCriterion("lock_id not like", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdIn(List<String> values) {
            addCriterion("lock_id in", values, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotIn(List<String> values) {
            addCriterion("lock_id not in", values, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdBetween(String value1, String value2) {
            addCriterion("lock_id between", value1, value2, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotBetween(String value1, String value2) {
            addCriterion("lock_id not between", value1, value2, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockTypeIsNull() {
            addCriterion("lock_type is null");
            return (Criteria) this;
        }

        public Criteria andLockTypeIsNotNull() {
            addCriterion("lock_type is not null");
            return (Criteria) this;
        }

        public Criteria andLockTypeEqualTo(String value) {
            addCriterion("lock_type =", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeNotEqualTo(String value) {
            addCriterion("lock_type <>", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeGreaterThan(String value) {
            addCriterion("lock_type >", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeGreaterThanOrEqualTo(String value) {
            addCriterion("lock_type >=", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeLessThan(String value) {
            addCriterion("lock_type <", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeLessThanOrEqualTo(String value) {
            addCriterion("lock_type <=", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeLike(String value) {
            addCriterion("lock_type like", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeNotLike(String value) {
            addCriterion("lock_type not like", value, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeIn(List<String> values) {
            addCriterion("lock_type in", values, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeNotIn(List<String> values) {
            addCriterion("lock_type not in", values, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeBetween(String value1, String value2) {
            addCriterion("lock_type between", value1, value2, "lockType");
            return (Criteria) this;
        }

        public Criteria andLockTypeNotBetween(String value1, String value2) {
            addCriterion("lock_type not between", value1, value2, "lockType");
            return (Criteria) this;
        }

        public Criteria andGrantIdIsNull() {
            addCriterion("grant_id is null");
            return (Criteria) this;
        }

        public Criteria andGrantIdIsNotNull() {
            addCriterion("grant_id is not null");
            return (Criteria) this;
        }

        public Criteria andGrantIdEqualTo(String value) {
            addCriterion("grant_id =", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdNotEqualTo(String value) {
            addCriterion("grant_id <>", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdGreaterThan(String value) {
            addCriterion("grant_id >", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdGreaterThanOrEqualTo(String value) {
            addCriterion("grant_id >=", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdLessThan(String value) {
            addCriterion("grant_id <", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdLessThanOrEqualTo(String value) {
            addCriterion("grant_id <=", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdLike(String value) {
            addCriterion("grant_id like", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdNotLike(String value) {
            addCriterion("grant_id not like", value, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdIn(List<String> values) {
            addCriterion("grant_id in", values, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdNotIn(List<String> values) {
            addCriterion("grant_id not in", values, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdBetween(String value1, String value2) {
            addCriterion("grant_id between", value1, value2, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantIdNotBetween(String value1, String value2) {
            addCriterion("grant_id not between", value1, value2, "grantId");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtIsNull() {
            addCriterion("grant_start_at is null");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtIsNotNull() {
            addCriterion("grant_start_at is not null");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtEqualTo(String value) {
            addCriterion("grant_start_at =", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtNotEqualTo(String value) {
            addCriterion("grant_start_at <>", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtGreaterThan(String value) {
            addCriterion("grant_start_at >", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtGreaterThanOrEqualTo(String value) {
            addCriterion("grant_start_at >=", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtLessThan(String value) {
            addCriterion("grant_start_at <", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtLessThanOrEqualTo(String value) {
            addCriterion("grant_start_at <=", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtLike(String value) {
            addCriterion("grant_start_at like", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtNotLike(String value) {
            addCriterion("grant_start_at not like", value, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtIn(List<String> values) {
            addCriterion("grant_start_at in", values, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtNotIn(List<String> values) {
            addCriterion("grant_start_at not in", values, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtBetween(String value1, String value2) {
            addCriterion("grant_start_at between", value1, value2, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantStartAtNotBetween(String value1, String value2) {
            addCriterion("grant_start_at not between", value1, value2, "grantStartAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtIsNull() {
            addCriterion("grant_end_at is null");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtIsNotNull() {
            addCriterion("grant_end_at is not null");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtEqualTo(String value) {
            addCriterion("grant_end_at =", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtNotEqualTo(String value) {
            addCriterion("grant_end_at <>", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtGreaterThan(String value) {
            addCriterion("grant_end_at >", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtGreaterThanOrEqualTo(String value) {
            addCriterion("grant_end_at >=", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtLessThan(String value) {
            addCriterion("grant_end_at <", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtLessThanOrEqualTo(String value) {
            addCriterion("grant_end_at <=", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtLike(String value) {
            addCriterion("grant_end_at like", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtNotLike(String value) {
            addCriterion("grant_end_at not like", value, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtIn(List<String> values) {
            addCriterion("grant_end_at in", values, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtNotIn(List<String> values) {
            addCriterion("grant_end_at not in", values, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtBetween(String value1, String value2) {
            addCriterion("grant_end_at between", value1, value2, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantEndAtNotBetween(String value1, String value2) {
            addCriterion("grant_end_at not between", value1, value2, "grantEndAt");
            return (Criteria) this;
        }

        public Criteria andGrantMsgIsNull() {
            addCriterion("grant_msg is null");
            return (Criteria) this;
        }

        public Criteria andGrantMsgIsNotNull() {
            addCriterion("grant_msg is not null");
            return (Criteria) this;
        }

        public Criteria andGrantMsgEqualTo(String value) {
            addCriterion("grant_msg =", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgNotEqualTo(String value) {
            addCriterion("grant_msg <>", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgGreaterThan(String value) {
            addCriterion("grant_msg >", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgGreaterThanOrEqualTo(String value) {
            addCriterion("grant_msg >=", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgLessThan(String value) {
            addCriterion("grant_msg <", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgLessThanOrEqualTo(String value) {
            addCriterion("grant_msg <=", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgLike(String value) {
            addCriterion("grant_msg like", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgNotLike(String value) {
            addCriterion("grant_msg not like", value, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgIn(List<String> values) {
            addCriterion("grant_msg in", values, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgNotIn(List<String> values) {
            addCriterion("grant_msg not in", values, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgBetween(String value1, String value2) {
            addCriterion("grant_msg between", value1, value2, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andGrantMsgNotBetween(String value1, String value2) {
            addCriterion("grant_msg not between", value1, value2, "grantMsg");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeIsNull() {
            addCriterion("last_unlock_datatime is null");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeIsNotNull() {
            addCriterion("last_unlock_datatime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeEqualTo(String value) {
            addCriterion("last_unlock_datatime =", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeNotEqualTo(String value) {
            addCriterion("last_unlock_datatime <>", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeGreaterThan(String value) {
            addCriterion("last_unlock_datatime >", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeGreaterThanOrEqualTo(String value) {
            addCriterion("last_unlock_datatime >=", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeLessThan(String value) {
            addCriterion("last_unlock_datatime <", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeLessThanOrEqualTo(String value) {
            addCriterion("last_unlock_datatime <=", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeLike(String value) {
            addCriterion("last_unlock_datatime like", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeNotLike(String value) {
            addCriterion("last_unlock_datatime not like", value, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeIn(List<String> values) {
            addCriterion("last_unlock_datatime in", values, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeNotIn(List<String> values) {
            addCriterion("last_unlock_datatime not in", values, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeBetween(String value1, String value2) {
            addCriterion("last_unlock_datatime between", value1, value2, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatatimeNotBetween(String value1, String value2) {
            addCriterion("last_unlock_datatime not between", value1, value2, "lastUnlockDatatime");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesIsNull() {
            addCriterion("unlock_times is null");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesIsNotNull() {
            addCriterion("unlock_times is not null");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesEqualTo(Integer value) {
            addCriterion("unlock_times =", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesNotEqualTo(Integer value) {
            addCriterion("unlock_times <>", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesGreaterThan(Integer value) {
            addCriterion("unlock_times >", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("unlock_times >=", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesLessThan(Integer value) {
            addCriterion("unlock_times <", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesLessThanOrEqualTo(Integer value) {
            addCriterion("unlock_times <=", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesIn(List<Integer> values) {
            addCriterion("unlock_times in", values, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesNotIn(List<Integer> values) {
            addCriterion("unlock_times not in", values, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesBetween(Integer value1, Integer value2) {
            addCriterion("unlock_times between", value1, value2, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("unlock_times not between", value1, value2, "unlockTimes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 22 22:34:38 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_yee_lock_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}