package com.dominator.entity;

import java.util.ArrayList;
import java.util.List;

public class TblYeeLockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public TblYeeLockExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLockIdIsNull() {
            addCriterion("lock_id is null");
            return (Criteria) this;
        }

        public Criteria andLockIdIsNotNull() {
            addCriterion("lock_id is not null");
            return (Criteria) this;
        }

        public Criteria andLockIdEqualTo(String value) {
            addCriterion("lock_id =", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotEqualTo(String value) {
            addCriterion("lock_id <>", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdGreaterThan(String value) {
            addCriterion("lock_id >", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdGreaterThanOrEqualTo(String value) {
            addCriterion("lock_id >=", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdLessThan(String value) {
            addCriterion("lock_id <", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdLessThanOrEqualTo(String value) {
            addCriterion("lock_id <=", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdLike(String value) {
            addCriterion("lock_id like", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotLike(String value) {
            addCriterion("lock_id not like", value, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdIn(List<String> values) {
            addCriterion("lock_id in", values, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotIn(List<String> values) {
            addCriterion("lock_id not in", values, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdBetween(String value1, String value2) {
            addCriterion("lock_id between", value1, value2, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockIdNotBetween(String value1, String value2) {
            addCriterion("lock_id not between", value1, value2, "lockId");
            return (Criteria) this;
        }

        public Criteria andLockSnIsNull() {
            addCriterion("lock_sn is null");
            return (Criteria) this;
        }

        public Criteria andLockSnIsNotNull() {
            addCriterion("lock_sn is not null");
            return (Criteria) this;
        }

        public Criteria andLockSnEqualTo(String value) {
            addCriterion("lock_sn =", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnNotEqualTo(String value) {
            addCriterion("lock_sn <>", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnGreaterThan(String value) {
            addCriterion("lock_sn >", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnGreaterThanOrEqualTo(String value) {
            addCriterion("lock_sn >=", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnLessThan(String value) {
            addCriterion("lock_sn <", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnLessThanOrEqualTo(String value) {
            addCriterion("lock_sn <=", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnLike(String value) {
            addCriterion("lock_sn like", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnNotLike(String value) {
            addCriterion("lock_sn not like", value, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnIn(List<String> values) {
            addCriterion("lock_sn in", values, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnNotIn(List<String> values) {
            addCriterion("lock_sn not in", values, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnBetween(String value1, String value2) {
            addCriterion("lock_sn between", value1, value2, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockSnNotBetween(String value1, String value2) {
            addCriterion("lock_sn not between", value1, value2, "lockSn");
            return (Criteria) this;
        }

        public Criteria andLockKeyIsNull() {
            addCriterion("lock_key is null");
            return (Criteria) this;
        }

        public Criteria andLockKeyIsNotNull() {
            addCriterion("lock_key is not null");
            return (Criteria) this;
        }

        public Criteria andLockKeyEqualTo(String value) {
            addCriterion("lock_key =", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyNotEqualTo(String value) {
            addCriterion("lock_key <>", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyGreaterThan(String value) {
            addCriterion("lock_key >", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyGreaterThanOrEqualTo(String value) {
            addCriterion("lock_key >=", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyLessThan(String value) {
            addCriterion("lock_key <", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyLessThanOrEqualTo(String value) {
            addCriterion("lock_key <=", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyLike(String value) {
            addCriterion("lock_key like", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyNotLike(String value) {
            addCriterion("lock_key not like", value, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyIn(List<String> values) {
            addCriterion("lock_key in", values, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyNotIn(List<String> values) {
            addCriterion("lock_key not in", values, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyBetween(String value1, String value2) {
            addCriterion("lock_key between", value1, value2, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockKeyNotBetween(String value1, String value2) {
            addCriterion("lock_key not between", value1, value2, "lockKey");
            return (Criteria) this;
        }

        public Criteria andLockNameIsNull() {
            addCriterion("lock_name is null");
            return (Criteria) this;
        }

        public Criteria andLockNameIsNotNull() {
            addCriterion("lock_name is not null");
            return (Criteria) this;
        }

        public Criteria andLockNameEqualTo(String value) {
            addCriterion("lock_name =", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameNotEqualTo(String value) {
            addCriterion("lock_name <>", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameGreaterThan(String value) {
            addCriterion("lock_name >", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameGreaterThanOrEqualTo(String value) {
            addCriterion("lock_name >=", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameLessThan(String value) {
            addCriterion("lock_name <", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameLessThanOrEqualTo(String value) {
            addCriterion("lock_name <=", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameLike(String value) {
            addCriterion("lock_name like", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameNotLike(String value) {
            addCriterion("lock_name not like", value, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameIn(List<String> values) {
            addCriterion("lock_name in", values, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameNotIn(List<String> values) {
            addCriterion("lock_name not in", values, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameBetween(String value1, String value2) {
            addCriterion("lock_name between", value1, value2, "lockName");
            return (Criteria) this;
        }

        public Criteria andLockNameNotBetween(String value1, String value2) {
            addCriterion("lock_name not between", value1, value2, "lockName");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(String value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(String value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(String value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(String value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(String value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(String value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLike(String value) {
            addCriterion("add_time like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotLike(String value) {
            addCriterion("add_time not like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<String> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<String> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(String value1, String value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(String value1, String value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeIsNull() {
            addCriterion("last_unlock_datetime is null");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeIsNotNull() {
            addCriterion("last_unlock_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeEqualTo(String value) {
            addCriterion("last_unlock_datetime =", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeNotEqualTo(String value) {
            addCriterion("last_unlock_datetime <>", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeGreaterThan(String value) {
            addCriterion("last_unlock_datetime >", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("last_unlock_datetime >=", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeLessThan(String value) {
            addCriterion("last_unlock_datetime <", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeLessThanOrEqualTo(String value) {
            addCriterion("last_unlock_datetime <=", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeLike(String value) {
            addCriterion("last_unlock_datetime like", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeNotLike(String value) {
            addCriterion("last_unlock_datetime not like", value, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeIn(List<String> values) {
            addCriterion("last_unlock_datetime in", values, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeNotIn(List<String> values) {
            addCriterion("last_unlock_datetime not in", values, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeBetween(String value1, String value2) {
            addCriterion("last_unlock_datetime between", value1, value2, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUnlockDatetimeNotBetween(String value1, String value2) {
            addCriterion("last_unlock_datetime not between", value1, value2, "lastUnlockDatetime");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesIsNull() {
            addCriterion("unlock_times is null");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesIsNotNull() {
            addCriterion("unlock_times is not null");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesEqualTo(Integer value) {
            addCriterion("unlock_times =", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesNotEqualTo(Integer value) {
            addCriterion("unlock_times <>", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesGreaterThan(Integer value) {
            addCriterion("unlock_times >", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("unlock_times >=", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesLessThan(Integer value) {
            addCriterion("unlock_times <", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesLessThanOrEqualTo(Integer value) {
            addCriterion("unlock_times <=", value, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesIn(List<Integer> values) {
            addCriterion("unlock_times in", values, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesNotIn(List<Integer> values) {
            addCriterion("unlock_times not in", values, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesBetween(Integer value1, Integer value2) {
            addCriterion("unlock_times between", value1, value2, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andUnlockTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("unlock_times not between", value1, value2, "unlockTimes");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(String value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(String value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(String value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(String value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(String value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(String value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLike(String value) {
            addCriterion("is_valid like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotLike(String value) {
            addCriterion("is_valid not like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<String> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<String> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(String value1, String value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(String value1, String value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 22 22:34:38 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_yee_lock
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}