package com.dominator.entity;

public class TblYeeLockUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.user_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.user_name
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.lock_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String lockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.lock_type
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String lockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.grant_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String grantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.grant_start_at
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String grantStartAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.grant_end_at
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String grantEndAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.grant_msg
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String grantMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.type
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.last_unlock_datatime
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private String lastUnlockDatatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_yee_lock_user.unlock_times
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    private Integer unlockTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.user_id
     *
     * @return the value of tbl_yee_lock_user.user_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.user_id
     *
     * @param userId the value for tbl_yee_lock_user.user_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.user_name
     *
     * @return the value of tbl_yee_lock_user.user_name
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.user_name
     *
     * @param userName the value for tbl_yee_lock_user.user_name
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.lock_id
     *
     * @return the value of tbl_yee_lock_user.lock_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getLockId() {
        return lockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.lock_id
     *
     * @param lockId the value for tbl_yee_lock_user.lock_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setLockId(String lockId) {
        this.lockId = lockId == null ? null : lockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.lock_type
     *
     * @return the value of tbl_yee_lock_user.lock_type
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getLockType() {
        return lockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.lock_type
     *
     * @param lockType the value for tbl_yee_lock_user.lock_type
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setLockType(String lockType) {
        this.lockType = lockType == null ? null : lockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.grant_id
     *
     * @return the value of tbl_yee_lock_user.grant_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getGrantId() {
        return grantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.grant_id
     *
     * @param grantId the value for tbl_yee_lock_user.grant_id
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setGrantId(String grantId) {
        this.grantId = grantId == null ? null : grantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.grant_start_at
     *
     * @return the value of tbl_yee_lock_user.grant_start_at
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getGrantStartAt() {
        return grantStartAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.grant_start_at
     *
     * @param grantStartAt the value for tbl_yee_lock_user.grant_start_at
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setGrantStartAt(String grantStartAt) {
        this.grantStartAt = grantStartAt == null ? null : grantStartAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.grant_end_at
     *
     * @return the value of tbl_yee_lock_user.grant_end_at
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getGrantEndAt() {
        return grantEndAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.grant_end_at
     *
     * @param grantEndAt the value for tbl_yee_lock_user.grant_end_at
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setGrantEndAt(String grantEndAt) {
        this.grantEndAt = grantEndAt == null ? null : grantEndAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.grant_msg
     *
     * @return the value of tbl_yee_lock_user.grant_msg
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getGrantMsg() {
        return grantMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.grant_msg
     *
     * @param grantMsg the value for tbl_yee_lock_user.grant_msg
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setGrantMsg(String grantMsg) {
        this.grantMsg = grantMsg == null ? null : grantMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.type
     *
     * @return the value of tbl_yee_lock_user.type
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.type
     *
     * @param type the value for tbl_yee_lock_user.type
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.last_unlock_datatime
     *
     * @return the value of tbl_yee_lock_user.last_unlock_datatime
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public String getLastUnlockDatatime() {
        return lastUnlockDatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.last_unlock_datatime
     *
     * @param lastUnlockDatatime the value for tbl_yee_lock_user.last_unlock_datatime
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setLastUnlockDatatime(String lastUnlockDatatime) {
        this.lastUnlockDatatime = lastUnlockDatatime == null ? null : lastUnlockDatatime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_yee_lock_user.unlock_times
     *
     * @return the value of tbl_yee_lock_user.unlock_times
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public Integer getUnlockTimes() {
        return unlockTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_yee_lock_user.unlock_times
     *
     * @param unlockTimes the value for tbl_yee_lock_user.unlock_times
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    public void setUnlockTimes(Integer unlockTimes) {
        this.unlockTimes = unlockTimes;
    }
}