package com.dominator.entity;

import java.util.Date;

public class TConsult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.property_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.name
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.contact_name
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.phone_num
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.logo
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.subtitle
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.detail
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.pics
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String pics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.status
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.create_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.modify_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.modify_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consult.is_valid
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.id
     *
     * @return the value of t_consult.id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.id
     *
     * @param id the value for t_consult.id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.property_id
     *
     * @return the value of t_consult.property_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.property_id
     *
     * @param propertyId the value for t_consult.property_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId == null ? null : propertyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.name
     *
     * @return the value of t_consult.name
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.name
     *
     * @param name the value for t_consult.name
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.contact_name
     *
     * @return the value of t_consult.contact_name
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.contact_name
     *
     * @param contactName the value for t_consult.contact_name
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.phone_num
     *
     * @return the value of t_consult.phone_num
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.phone_num
     *
     * @param phoneNum the value for t_consult.phone_num
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.logo
     *
     * @return the value of t_consult.logo
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.logo
     *
     * @param logo the value for t_consult.logo
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.subtitle
     *
     * @return the value of t_consult.subtitle
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.subtitle
     *
     * @param subtitle the value for t_consult.subtitle
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.detail
     *
     * @return the value of t_consult.detail
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.detail
     *
     * @param detail the value for t_consult.detail
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.pics
     *
     * @return the value of t_consult.pics
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.pics
     *
     * @param pics the value for t_consult.pics
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.status
     *
     * @return the value of t_consult.status
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.status
     *
     * @param status the value for t_consult.status
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.create_time
     *
     * @return the value of t_consult.create_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.create_time
     *
     * @param createTime the value for t_consult.create_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.modify_time
     *
     * @return the value of t_consult.modify_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.modify_time
     *
     * @param modifyTime the value for t_consult.modify_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.modify_id
     *
     * @return the value of t_consult.modify_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.modify_id
     *
     * @param modifyId the value for t_consult.modify_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consult.is_valid
     *
     * @return the value of t_consult.is_valid
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consult.is_valid
     *
     * @param isValid the value for t_consult.is_valid
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }
}