package com.dominator.entity;

import java.util.Date;

public class THfProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.property_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.mer_cust_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String merCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.acct_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String acctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.modify_time
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.create_time
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.modify_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hf_property.is_valid
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    private String isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.id
     *
     * @return the value of t_hf_property.id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.id
     *
     * @param id the value for t_hf_property.id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.property_id
     *
     * @return the value of t_hf_property.property_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.property_id
     *
     * @param propertyId the value for t_hf_property.property_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId == null ? null : propertyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.mer_cust_id
     *
     * @return the value of t_hf_property.mer_cust_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getMerCustId() {
        return merCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.mer_cust_id
     *
     * @param merCustId the value for t_hf_property.mer_cust_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setMerCustId(String merCustId) {
        this.merCustId = merCustId == null ? null : merCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.acct_id
     *
     * @return the value of t_hf_property.acct_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.acct_id
     *
     * @param acctId the value for t_hf_property.acct_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setAcctId(String acctId) {
        this.acctId = acctId == null ? null : acctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.modify_time
     *
     * @return the value of t_hf_property.modify_time
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.modify_time
     *
     * @param modifyTime the value for t_hf_property.modify_time
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.create_time
     *
     * @return the value of t_hf_property.create_time
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.create_time
     *
     * @param createTime the value for t_hf_property.create_time
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.modify_id
     *
     * @return the value of t_hf_property.modify_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.modify_id
     *
     * @param modifyId the value for t_hf_property.modify_id
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hf_property.is_valid
     *
     * @return the value of t_hf_property.is_valid
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hf_property.is_valid
     *
     * @param isValid the value for t_hf_property.is_valid
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }
}