package com.dominator.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TRepairExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public TRepairExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andGardenIdIsNull() {
            addCriterion("garden_id is null");
            return (Criteria) this;
        }

        public Criteria andGardenIdIsNotNull() {
            addCriterion("garden_id is not null");
            return (Criteria) this;
        }

        public Criteria andGardenIdEqualTo(String value) {
            addCriterion("garden_id =", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdNotEqualTo(String value) {
            addCriterion("garden_id <>", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdGreaterThan(String value) {
            addCriterion("garden_id >", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdGreaterThanOrEqualTo(String value) {
            addCriterion("garden_id >=", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdLessThan(String value) {
            addCriterion("garden_id <", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdLessThanOrEqualTo(String value) {
            addCriterion("garden_id <=", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdLike(String value) {
            addCriterion("garden_id like", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdNotLike(String value) {
            addCriterion("garden_id not like", value, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdIn(List<String> values) {
            addCriterion("garden_id in", values, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdNotIn(List<String> values) {
            addCriterion("garden_id not in", values, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdBetween(String value1, String value2) {
            addCriterion("garden_id between", value1, value2, "gardenId");
            return (Criteria) this;
        }

        public Criteria andGardenIdNotBetween(String value1, String value2) {
            addCriterion("garden_id not between", value1, value2, "gardenId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdIsNull() {
            addCriterion("repair_user_id is null");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdIsNotNull() {
            addCriterion("repair_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdEqualTo(String value) {
            addCriterion("repair_user_id =", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdNotEqualTo(String value) {
            addCriterion("repair_user_id <>", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdGreaterThan(String value) {
            addCriterion("repair_user_id >", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("repair_user_id >=", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdLessThan(String value) {
            addCriterion("repair_user_id <", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdLessThanOrEqualTo(String value) {
            addCriterion("repair_user_id <=", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdLike(String value) {
            addCriterion("repair_user_id like", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdNotLike(String value) {
            addCriterion("repair_user_id not like", value, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdIn(List<String> values) {
            addCriterion("repair_user_id in", values, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdNotIn(List<String> values) {
            addCriterion("repair_user_id not in", values, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdBetween(String value1, String value2) {
            addCriterion("repair_user_id between", value1, value2, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andRepairUserIdNotBetween(String value1, String value2) {
            addCriterion("repair_user_id not between", value1, value2, "repairUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdIsNull() {
            addCriterion("fix_user_id is null");
            return (Criteria) this;
        }

        public Criteria andFixUserIdIsNotNull() {
            addCriterion("fix_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andFixUserIdEqualTo(String value) {
            addCriterion("fix_user_id =", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdNotEqualTo(String value) {
            addCriterion("fix_user_id <>", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdGreaterThan(String value) {
            addCriterion("fix_user_id >", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("fix_user_id >=", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdLessThan(String value) {
            addCriterion("fix_user_id <", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdLessThanOrEqualTo(String value) {
            addCriterion("fix_user_id <=", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdLike(String value) {
            addCriterion("fix_user_id like", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdNotLike(String value) {
            addCriterion("fix_user_id not like", value, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdIn(List<String> values) {
            addCriterion("fix_user_id in", values, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdNotIn(List<String> values) {
            addCriterion("fix_user_id not in", values, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdBetween(String value1, String value2) {
            addCriterion("fix_user_id between", value1, value2, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andFixUserIdNotBetween(String value1, String value2) {
            addCriterion("fix_user_id not between", value1, value2, "fixUserId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSpotIsNull() {
            addCriterion("spot is null");
            return (Criteria) this;
        }

        public Criteria andSpotIsNotNull() {
            addCriterion("spot is not null");
            return (Criteria) this;
        }

        public Criteria andSpotEqualTo(String value) {
            addCriterion("spot =", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotNotEqualTo(String value) {
            addCriterion("spot <>", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotGreaterThan(String value) {
            addCriterion("spot >", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotGreaterThanOrEqualTo(String value) {
            addCriterion("spot >=", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotLessThan(String value) {
            addCriterion("spot <", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotLessThanOrEqualTo(String value) {
            addCriterion("spot <=", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotLike(String value) {
            addCriterion("spot like", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotNotLike(String value) {
            addCriterion("spot not like", value, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotIn(List<String> values) {
            addCriterion("spot in", values, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotNotIn(List<String> values) {
            addCriterion("spot not in", values, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotBetween(String value1, String value2) {
            addCriterion("spot between", value1, value2, "spot");
            return (Criteria) this;
        }

        public Criteria andSpotNotBetween(String value1, String value2) {
            addCriterion("spot not between", value1, value2, "spot");
            return (Criteria) this;
        }

        public Criteria andRepairNumIsNull() {
            addCriterion("repair_num is null");
            return (Criteria) this;
        }

        public Criteria andRepairNumIsNotNull() {
            addCriterion("repair_num is not null");
            return (Criteria) this;
        }

        public Criteria andRepairNumEqualTo(String value) {
            addCriterion("repair_num =", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumNotEqualTo(String value) {
            addCriterion("repair_num <>", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumGreaterThan(String value) {
            addCriterion("repair_num >", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumGreaterThanOrEqualTo(String value) {
            addCriterion("repair_num >=", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumLessThan(String value) {
            addCriterion("repair_num <", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumLessThanOrEqualTo(String value) {
            addCriterion("repair_num <=", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumLike(String value) {
            addCriterion("repair_num like", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumNotLike(String value) {
            addCriterion("repair_num not like", value, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumIn(List<String> values) {
            addCriterion("repair_num in", values, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumNotIn(List<String> values) {
            addCriterion("repair_num not in", values, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumBetween(String value1, String value2) {
            addCriterion("repair_num between", value1, value2, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairNumNotBetween(String value1, String value2) {
            addCriterion("repair_num not between", value1, value2, "repairNum");
            return (Criteria) this;
        }

        public Criteria andRepairContentIsNull() {
            addCriterion("repair_content is null");
            return (Criteria) this;
        }

        public Criteria andRepairContentIsNotNull() {
            addCriterion("repair_content is not null");
            return (Criteria) this;
        }

        public Criteria andRepairContentEqualTo(String value) {
            addCriterion("repair_content =", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentNotEqualTo(String value) {
            addCriterion("repair_content <>", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentGreaterThan(String value) {
            addCriterion("repair_content >", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentGreaterThanOrEqualTo(String value) {
            addCriterion("repair_content >=", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentLessThan(String value) {
            addCriterion("repair_content <", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentLessThanOrEqualTo(String value) {
            addCriterion("repair_content <=", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentLike(String value) {
            addCriterion("repair_content like", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentNotLike(String value) {
            addCriterion("repair_content not like", value, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentIn(List<String> values) {
            addCriterion("repair_content in", values, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentNotIn(List<String> values) {
            addCriterion("repair_content not in", values, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentBetween(String value1, String value2) {
            addCriterion("repair_content between", value1, value2, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairContentNotBetween(String value1, String value2) {
            addCriterion("repair_content not between", value1, value2, "repairContent");
            return (Criteria) this;
        }

        public Criteria andRepairPicsIsNull() {
            addCriterion("repair_pics is null");
            return (Criteria) this;
        }

        public Criteria andRepairPicsIsNotNull() {
            addCriterion("repair_pics is not null");
            return (Criteria) this;
        }

        public Criteria andRepairPicsEqualTo(String value) {
            addCriterion("repair_pics =", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsNotEqualTo(String value) {
            addCriterion("repair_pics <>", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsGreaterThan(String value) {
            addCriterion("repair_pics >", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsGreaterThanOrEqualTo(String value) {
            addCriterion("repair_pics >=", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsLessThan(String value) {
            addCriterion("repair_pics <", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsLessThanOrEqualTo(String value) {
            addCriterion("repair_pics <=", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsLike(String value) {
            addCriterion("repair_pics like", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsNotLike(String value) {
            addCriterion("repair_pics not like", value, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsIn(List<String> values) {
            addCriterion("repair_pics in", values, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsNotIn(List<String> values) {
            addCriterion("repair_pics not in", values, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsBetween(String value1, String value2) {
            addCriterion("repair_pics between", value1, value2, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairPicsNotBetween(String value1, String value2) {
            addCriterion("repair_pics not between", value1, value2, "repairPics");
            return (Criteria) this;
        }

        public Criteria andRepairStatusIsNull() {
            addCriterion("repair_status is null");
            return (Criteria) this;
        }

        public Criteria andRepairStatusIsNotNull() {
            addCriterion("repair_status is not null");
            return (Criteria) this;
        }

        public Criteria andRepairStatusEqualTo(String value) {
            addCriterion("repair_status =", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusNotEqualTo(String value) {
            addCriterion("repair_status <>", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusGreaterThan(String value) {
            addCriterion("repair_status >", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusGreaterThanOrEqualTo(String value) {
            addCriterion("repair_status >=", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusLessThan(String value) {
            addCriterion("repair_status <", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusLessThanOrEqualTo(String value) {
            addCriterion("repair_status <=", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusLike(String value) {
            addCriterion("repair_status like", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusNotLike(String value) {
            addCriterion("repair_status not like", value, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusIn(List<String> values) {
            addCriterion("repair_status in", values, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusNotIn(List<String> values) {
            addCriterion("repair_status not in", values, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusBetween(String value1, String value2) {
            addCriterion("repair_status between", value1, value2, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairStatusNotBetween(String value1, String value2) {
            addCriterion("repair_status not between", value1, value2, "repairStatus");
            return (Criteria) this;
        }

        public Criteria andRepairTimeIsNull() {
            addCriterion("repair_time is null");
            return (Criteria) this;
        }

        public Criteria andRepairTimeIsNotNull() {
            addCriterion("repair_time is not null");
            return (Criteria) this;
        }

        public Criteria andRepairTimeEqualTo(Date value) {
            addCriterion("repair_time =", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeNotEqualTo(Date value) {
            addCriterion("repair_time <>", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeGreaterThan(Date value) {
            addCriterion("repair_time >", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("repair_time >=", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeLessThan(Date value) {
            addCriterion("repair_time <", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeLessThanOrEqualTo(Date value) {
            addCriterion("repair_time <=", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeIn(List<Date> values) {
            addCriterion("repair_time in", values, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeNotIn(List<Date> values) {
            addCriterion("repair_time not in", values, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeBetween(Date value1, Date value2) {
            addCriterion("repair_time between", value1, value2, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeNotBetween(Date value1, Date value2) {
            addCriterion("repair_time not between", value1, value2, "repairTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeIsNull() {
            addCriterion("assign_time is null");
            return (Criteria) this;
        }

        public Criteria andAssignTimeIsNotNull() {
            addCriterion("assign_time is not null");
            return (Criteria) this;
        }

        public Criteria andAssignTimeEqualTo(Date value) {
            addCriterion("assign_time =", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeNotEqualTo(Date value) {
            addCriterion("assign_time <>", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeGreaterThan(Date value) {
            addCriterion("assign_time >", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("assign_time >=", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeLessThan(Date value) {
            addCriterion("assign_time <", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeLessThanOrEqualTo(Date value) {
            addCriterion("assign_time <=", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeIn(List<Date> values) {
            addCriterion("assign_time in", values, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeNotIn(List<Date> values) {
            addCriterion("assign_time not in", values, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeBetween(Date value1, Date value2) {
            addCriterion("assign_time between", value1, value2, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeNotBetween(Date value1, Date value2) {
            addCriterion("assign_time not between", value1, value2, "assignTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNull() {
            addCriterion("complete_time is null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNotNull() {
            addCriterion("complete_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeEqualTo(Date value) {
            addCriterion("complete_time =", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotEqualTo(Date value) {
            addCriterion("complete_time <>", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThan(Date value) {
            addCriterion("complete_time >", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("complete_time >=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThan(Date value) {
            addCriterion("complete_time <", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("complete_time <=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIn(List<Date> values) {
            addCriterion("complete_time in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotIn(List<Date> values) {
            addCriterion("complete_time not in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("complete_time between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("complete_time not between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNull() {
            addCriterion("modify_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNotNull() {
            addCriterion("modify_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIdEqualTo(String value) {
            addCriterion("modify_id =", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotEqualTo(String value) {
            addCriterion("modify_id <>", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThan(String value) {
            addCriterion("modify_id >", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThanOrEqualTo(String value) {
            addCriterion("modify_id >=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThan(String value) {
            addCriterion("modify_id <", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThanOrEqualTo(String value) {
            addCriterion("modify_id <=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLike(String value) {
            addCriterion("modify_id like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotLike(String value) {
            addCriterion("modify_id not like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIn(List<String> values) {
            addCriterion("modify_id in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotIn(List<String> values) {
            addCriterion("modify_id not in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdBetween(String value1, String value2) {
            addCriterion("modify_id between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotBetween(String value1, String value2) {
            addCriterion("modify_id not between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(String value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(String value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(String value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(String value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(String value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(String value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLike(String value) {
            addCriterion("is_valid like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotLike(String value) {
            addCriterion("is_valid not like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<String> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<String> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(String value1, String value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(String value1, String value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_repair
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 18 10:02:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}