package com.dominator.entity;

import java.util.Date;

public class TRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.type
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.sort
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.modify_time
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_time
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.modify_id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.is_valid
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.unit_id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private String unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.modules_ids
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    private String modulesIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.type
     *
     * @return the value of t_role.type
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.type
     *
     * @param type the value for t_role.type
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.sort
     *
     * @return the value of t_role.sort
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.sort
     *
     * @param sort the value for t_role.sort
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.modify_time
     *
     * @return the value of t_role.modify_time
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.modify_time
     *
     * @param modifyTime the value for t_role.modify_time
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_time
     *
     * @return the value of t_role.create_time
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_time
     *
     * @param createTime the value for t_role.create_time
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.modify_id
     *
     * @return the value of t_role.modify_id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.modify_id
     *
     * @param modifyId the value for t_role.modify_id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.is_valid
     *
     * @return the value of t_role.is_valid
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.is_valid
     *
     * @param isValid the value for t_role.is_valid
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.unit_id
     *
     * @return the value of t_role.unit_id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.unit_id
     *
     * @param unitId the value for t_role.unit_id
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId == null ? null : unitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.modules_ids
     *
     * @return the value of t_role.modules_ids
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public String getModulesIds() {
        return modulesIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.modules_ids
     *
     * @param modulesIds the value for t_role.modules_ids
     *
     * @mbggenerated Mon Apr 16 00:57:24 CST 2018
     */
    public void setModulesIds(String modulesIds) {
        this.modulesIds = modulesIds == null ? null : modulesIds.trim();
    }
}