package com.dominator.entity;

import java.util.Date;

public class TSocialActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.title
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.picture_url
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.publisher_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String publisherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.publish_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.address
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.activity_desc
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String activityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.is_hearted
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String isHearted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.is_checked
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String isChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.checker
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String checker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.check_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.check_desc
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String checkDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.status
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.begin_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.create_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.is_valid
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.end_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.property_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.company_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.province
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.city
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.district
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_social_activity.address_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    private String addressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.id
     *
     * @return the value of t_social_activity.id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.id
     *
     * @param id the value for t_social_activity.id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.title
     *
     * @return the value of t_social_activity.title
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.title
     *
     * @param title the value for t_social_activity.title
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.picture_url
     *
     * @return the value of t_social_activity.picture_url
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.picture_url
     *
     * @param pictureUrl the value for t_social_activity.picture_url
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.publisher_id
     *
     * @return the value of t_social_activity.publisher_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.publisher_id
     *
     * @param publisherId the value for t_social_activity.publisher_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setPublisherId(String publisherId) {
        this.publisherId = publisherId == null ? null : publisherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.publish_time
     *
     * @return the value of t_social_activity.publish_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.publish_time
     *
     * @param publishTime the value for t_social_activity.publish_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.address
     *
     * @return the value of t_social_activity.address
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.address
     *
     * @param address the value for t_social_activity.address
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.activity_desc
     *
     * @return the value of t_social_activity.activity_desc
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getActivityDesc() {
        return activityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.activity_desc
     *
     * @param activityDesc the value for t_social_activity.activity_desc
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setActivityDesc(String activityDesc) {
        this.activityDesc = activityDesc == null ? null : activityDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.is_hearted
     *
     * @return the value of t_social_activity.is_hearted
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getIsHearted() {
        return isHearted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.is_hearted
     *
     * @param isHearted the value for t_social_activity.is_hearted
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setIsHearted(String isHearted) {
        this.isHearted = isHearted == null ? null : isHearted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.is_checked
     *
     * @return the value of t_social_activity.is_checked
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getIsChecked() {
        return isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.is_checked
     *
     * @param isChecked the value for t_social_activity.is_checked
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setIsChecked(String isChecked) {
        this.isChecked = isChecked == null ? null : isChecked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.checker
     *
     * @return the value of t_social_activity.checker
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.checker
     *
     * @param checker the value for t_social_activity.checker
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.check_time
     *
     * @return the value of t_social_activity.check_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.check_time
     *
     * @param checkTime the value for t_social_activity.check_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.check_desc
     *
     * @return the value of t_social_activity.check_desc
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getCheckDesc() {
        return checkDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.check_desc
     *
     * @param checkDesc the value for t_social_activity.check_desc
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setCheckDesc(String checkDesc) {
        this.checkDesc = checkDesc == null ? null : checkDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.status
     *
     * @return the value of t_social_activity.status
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.status
     *
     * @param status the value for t_social_activity.status
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.begin_time
     *
     * @return the value of t_social_activity.begin_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.begin_time
     *
     * @param beginTime the value for t_social_activity.begin_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.create_time
     *
     * @return the value of t_social_activity.create_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.create_time
     *
     * @param createTime the value for t_social_activity.create_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.is_valid
     *
     * @return the value of t_social_activity.is_valid
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.is_valid
     *
     * @param isValid the value for t_social_activity.is_valid
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.end_time
     *
     * @return the value of t_social_activity.end_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.end_time
     *
     * @param endTime the value for t_social_activity.end_time
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.property_id
     *
     * @return the value of t_social_activity.property_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.property_id
     *
     * @param propertyId the value for t_social_activity.property_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId == null ? null : propertyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.company_id
     *
     * @return the value of t_social_activity.company_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.company_id
     *
     * @param companyId the value for t_social_activity.company_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.province
     *
     * @return the value of t_social_activity.province
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.province
     *
     * @param province the value for t_social_activity.province
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.city
     *
     * @return the value of t_social_activity.city
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.city
     *
     * @param city the value for t_social_activity.city
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.district
     *
     * @return the value of t_social_activity.district
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.district
     *
     * @param district the value for t_social_activity.district
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_social_activity.address_id
     *
     * @return the value of t_social_activity.address_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_social_activity.address_id
     *
     * @param addressId the value for t_social_activity.address_id
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }
}