package com.dominator.mapper;

import com.dominator.entity.TBanner;
import com.dominator.entity.TBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int countByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int deleteByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int insert(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int insertSelective(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    List<TBanner> selectByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    TBanner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") TBanner record, @Param("example") TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int updateByExample(@Param("record") TBanner record, @Param("example") TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int updateByPrimaryKeySelective(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Apr 26 22:06:37 CST 2018
     */
    int updateByPrimaryKey(TBanner record);
}