package com.dominator.mapper;

import com.dominator.entity.TblWxopenAuthorizationCode;
import com.dominator.entity.TblWxopenAuthorizationCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblWxopenAuthorizationCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int countByExample(TblWxopenAuthorizationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByExample(TblWxopenAuthorizationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insert(TblWxopenAuthorizationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insertSelective(TblWxopenAuthorizationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    List<TblWxopenAuthorizationCode> selectByExample(TblWxopenAuthorizationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    TblWxopenAuthorizationCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") TblWxopenAuthorizationCode record, @Param("example") TblWxopenAuthorizationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExample(@Param("record") TblWxopenAuthorizationCode record, @Param("example") TblWxopenAuthorizationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKeySelective(TblWxopenAuthorizationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_code
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKey(TblWxopenAuthorizationCode record);
}