package com.dominator.mapper;

import com.dominator.entity.TblWxopenAuthorizerAccountInfo;
import com.dominator.entity.TblWxopenAuthorizerAccountInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TblWxopenAuthorizerAccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int countByExample(TblWxopenAuthorizerAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByExample(TblWxopenAuthorizerAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insert(TblWxopenAuthorizerAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insertSelective(TblWxopenAuthorizerAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    List<TblWxopenAuthorizerAccountInfo> selectByExample(TblWxopenAuthorizerAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    TblWxopenAuthorizerAccountInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") TblWxopenAuthorizerAccountInfo record, @Param("example") TblWxopenAuthorizerAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExample(@Param("record") TblWxopenAuthorizerAccountInfo record, @Param("example") TblWxopenAuthorizerAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKeySelective(TblWxopenAuthorizerAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorizer_account_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKey(TblWxopenAuthorizerAccountInfo record);
}