package com.dominator.mapper;

import com.dominator.entity.TblWebpageAccessToken;
import com.dominator.entity.TblWebpageAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblWebpageAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int countByExample(TblWebpageAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByExample(TblWebpageAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insert(TblWebpageAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insertSelective(TblWebpageAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    List<TblWebpageAccessToken> selectByExampleWithBLOBs(TblWebpageAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    List<TblWebpageAccessToken> selectByExample(TblWebpageAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    TblWebpageAccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") TblWebpageAccessToken record, @Param("example") TblWebpageAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TblWebpageAccessToken record, @Param("example") TblWebpageAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExample(@Param("record") TblWebpageAccessToken record, @Param("example") TblWebpageAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKeySelective(TblWebpageAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TblWebpageAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_webpage_access_token
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKey(TblWebpageAccessToken record);
}