package com.dominator.mapper;

import com.dominator.entity.TblWxopenAuthorizationInfo;
import com.dominator.entity.TblWxopenAuthorizationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblWxopenAuthorizationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int countByExample(TblWxopenAuthorizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByExample(TblWxopenAuthorizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insert(TblWxopenAuthorizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insertSelective(TblWxopenAuthorizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    List<TblWxopenAuthorizationInfo> selectByExample(TblWxopenAuthorizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    TblWxopenAuthorizationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") TblWxopenAuthorizationInfo record, @Param("example") TblWxopenAuthorizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExample(@Param("record") TblWxopenAuthorizationInfo record, @Param("example") TblWxopenAuthorizationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKeySelective(TblWxopenAuthorizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wxopen_authorization_info
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKey(TblWxopenAuthorizationInfo record);
}