package com.dominator.mapper;

import com.dominator.entity.TblYeeLockGrant;
import com.dominator.entity.TblYeeLockGrantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblYeeLockGrantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int countByExample(TblYeeLockGrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByExample(TblYeeLockGrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByPrimaryKey(String grantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insert(TblYeeLockGrant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insertSelective(TblYeeLockGrant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    List<TblYeeLockGrant> selectByExample(TblYeeLockGrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    TblYeeLockGrant selectByPrimaryKey(String grantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") TblYeeLockGrant record, @Param("example") TblYeeLockGrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExample(@Param("record") TblYeeLockGrant record, @Param("example") TblYeeLockGrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKeySelective(TblYeeLockGrant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_yee_lock_grant
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByPrimaryKey(TblYeeLockGrant record);
}