package com.dominator.mapper;

import com.dominator.entity.TGardenUserRole;
import com.dominator.entity.TGardenUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TGardenUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int countByExample(TGardenUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int deleteByExample(TGardenUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int insert(TGardenUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int insertSelective(TGardenUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    List<TGardenUserRole> selectByExample(TGardenUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    TGardenUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") TGardenUserRole record, @Param("example") TGardenUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int updateByExample(@Param("record") TGardenUserRole record, @Param("example") TGardenUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int updateByPrimaryKeySelective(TGardenUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_garden_user_role
     *
     * @mbggenerated Wed Apr 18 11:20:42 CST 2018
     */
    int updateByPrimaryKey(TGardenUserRole record);
}