package com.dominator.mapper;

import com.dominator.entity.TLoginInfo;
import com.dominator.entity.TLoginInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int countByExample(TLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int deleteByExample(TLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int insert(TLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int insertSelective(TLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    List<TLoginInfo> selectByExample(TLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    TLoginInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") TLoginInfo record, @Param("example") TLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByExample(@Param("record") TLoginInfo record, @Param("example") TLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByPrimaryKeySelective(TLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_info
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByPrimaryKey(TLoginInfo record);
}