package com.dominator.mapper;

import com.dominator.entity.TPropertyMerchant;
import com.dominator.entity.TPropertyMerchantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TPropertyMerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int countByExample(TPropertyMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int deleteByExample(TPropertyMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int insert(TPropertyMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int insertSelective(TPropertyMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    List<TPropertyMerchant> selectByExample(TPropertyMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    TPropertyMerchant selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") TPropertyMerchant record, @Param("example") TPropertyMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByExample(@Param("record") TPropertyMerchant record, @Param("example") TPropertyMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByPrimaryKeySelective(TPropertyMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_merchant
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByPrimaryKey(TPropertyMerchant record);
}