package com.dominator.mapper;

import com.dominator.entity.TRepair;
import com.dominator.entity.TRepairExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TRepairMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int countByExample(TRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int deleteByExample(TRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int insert(TRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int insertSelective(TRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    List<TRepair> selectByExample(TRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    TRepair selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") TRepair record, @Param("example") TRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int updateByExample(@Param("record") TRepair record, @Param("example") TRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int updateByPrimaryKeySelective(TRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repair
     *
     * @mbggenerated Wed Apr 18 10:02:33 CST 2018
     */
    int updateByPrimaryKey(TRepair record);
}