package com.dominator.mapper;

import com.dominator.entity.TSocialActivity;
import com.dominator.entity.TSocialActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TSocialActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int countByExample(TSocialActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int deleteByExample(TSocialActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int insert(TSocialActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int insertSelective(TSocialActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    List<TSocialActivity> selectByExample(TSocialActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    TSocialActivity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSocialActivity record, @Param("example") TSocialActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int updateByExample(@Param("record") TSocialActivity record, @Param("example") TSocialActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int updateByPrimaryKeySelective(TSocialActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_social_activity
     *
     * @mbggenerated Tue May 15 11:35:17 CST 2018
     */
    int updateByPrimaryKey(TSocialActivity record);
}