package com.dominator.mapper;

import com.dominator.entity.TVisitor;
import com.dominator.entity.TVisitorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TVisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int countByExample(TVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int deleteByExample(TVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int insert(TVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int insertSelective(TVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    List<TVisitor> selectByExample(TVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    TVisitor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") TVisitor record, @Param("example") TVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByExample(@Param("record") TVisitor record, @Param("example") TVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByPrimaryKeySelective(TVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Mar 29 14:47:43 CST 2018
     */
    int updateByPrimaryKey(TVisitor record);
}