package com.dominator.mapper;

import com.dominator.entity.VUnitUser;
import com.dominator.entity.VUnitUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VUnitUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_unit_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int countByExample(VUnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_unit_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int deleteByExample(VUnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_unit_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insert(VUnitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_unit_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int insertSelective(VUnitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_unit_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    List<VUnitUser> selectByExample(VUnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_unit_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") VUnitUser record, @Param("example") VUnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_unit_user
     *
     * @mbggenerated Sun Apr 22 22:34:38 CST 2018
     */
    int updateByExample(@Param("record") VUnitUser record, @Param("example") VUnitUserExample example);
}